---
abstract: 'module that the Wurfl Perl client to retrieve capabilities data from the Wurfl server'
author:
  - 'Uri Bruck <uri@bruck.co.il>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-WurflSimple
requires:
  APR::Table: 0
  Apache2::CmdParms: 0
  Apache2::Const: 0
  Apache2::Directive: 0
  Apache2::Module: 0
  Apache2::RequestRec: 0
  Apache2::ServerUtil: 0
  Apache::Test: 0
  Apache::TestUtil: 0
  Cache::File: 0
  Net::WURFL::ScientiaMobile: 0
  Net::WURFL::ScientiaMobile::Cache::Cookie: 0
  perl: 5.010
  strict: 0
  warnings: 0
version: 0.002
